kumuluzee:
  name: comments
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  discovery:
    etcd:
      hosts: http://192.168.29.109:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ImageMetadataDS
      etcd-health-check:
        type: liveness
        connection-url: http://192.168.29.109:2379
      http-health-check:
        type: liveness
        connection-url: https://google.com
